// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "gorest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/image/{product}": {
      "get": {
        "description": "Return the product Image.",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the product to display.",
            "name": "product",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the product.",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/price": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkPrice",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/product/{product}": {
      "get": {
        "description": "Returns title of to the product!",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the product.",
            "name": "product",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the product title.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid characters in \"product\" were provided."
          }
        }
      }
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "HTTP server in Go with Swagger endpoints definition.",
    "title": "gorest-api",
    "version": "0.1.0"
  },
  "paths": {
    "/image/{product}": {
      "get": {
        "description": "Return the product Image.",
        "produces": [
          "image/png"
        ],
        "parameters": [
          {
            "type": "string",
            "description": "The name of the product to display.",
            "name": "product",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the product.",
            "schema": {
              "type": "file"
            }
          }
        }
      }
    },
    "/price": {
      "get": {
        "produces": [
          "text/plain"
        ],
        "operationId": "checkPrice",
        "responses": {
          "200": {
            "description": "OK message.",
            "schema": {
              "type": "string",
              "enum": [
                "OK"
              ]
            }
          }
        }
      }
    },
    "/product/{product}": {
      "get": {
        "description": "Returns title of to the product!",
        "parameters": [
          {
            "type": "string",
            "description": "The name of the product.",
            "name": "product",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Returns the product title.",
            "schema": {
              "type": "string"
            }
          },
          "400": {
            "description": "Invalid characters in \"product\" were provided."
          }
        }
      }
    }
  }
}`))
}
