// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// CheckPriceHandlerFunc turns a function with the right signature into a check price handler
type CheckPriceHandlerFunc func(CheckPriceParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CheckPriceHandlerFunc) Handle(params CheckPriceParams) middleware.Responder {
	return fn(params)
}

// CheckPriceHandler interface for that can handle valid check price params
type CheckPriceHandler interface {
	Handle(CheckPriceParams) middleware.Responder
}

// NewCheckPrice creates a new http.Handler for the check price operation
func NewCheckPrice(ctx *middleware.Context, handler CheckPriceHandler) *CheckPrice {
	return &CheckPrice{Context: ctx, Handler: handler}
}

/*
	CheckPrice swagger:route GET /price checkPrice

CheckPrice check price API
*/
type CheckPrice struct {
	Context *middleware.Context
	Handler CheckPriceHandler
}

func (o *CheckPrice) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewCheckPriceParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
