// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetImageProductHandlerFunc turns a function with the right signature into a get image product handler
type GetImageProductHandlerFunc func(GetImageProductParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetImageProductHandlerFunc) Handle(params GetImageProductParams) middleware.Responder {
	return fn(params)
}

// GetImageProductHandler interface for that can handle valid get image product params
type GetImageProductHandler interface {
	Handle(GetImageProductParams) middleware.Responder
}

// NewGetImageProduct creates a new http.Handler for the get image product operation
func NewGetImageProduct(ctx *middleware.Context, handler GetImageProductHandler) *GetImageProduct {
	return &GetImageProduct{Context: ctx, Handler: handler}
}

/*
	GetImageProduct swagger:route GET /image/{product} getImageProduct

Return the product Image.
*/
type GetImageProduct struct {
	Context *middleware.Context
	Handler GetImageProductHandler
}

func (o *GetImageProduct) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetImageProductParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
