// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/strfmt"
)

// NewGetImageProductParams creates a new GetImageProductParams object
//
// There are no default values defined in the spec.
func NewGetImageProductParams() GetImageProductParams {

	return GetImageProductParams{}
}

// GetImageProductParams contains all the bound params for the get image product operation
// typically these are obtained from a http.Request
//
// swagger:parameters GetImageProduct
type GetImageProductParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The name of the product to display.
	  Required: true
	  In: path
	*/
	Product string
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewGetImageProductParams() beforehand.
func (o *GetImageProductParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rProduct, rhkProduct, _ := route.Params.GetOK("product")
	if err := o.bindProduct(rProduct, rhkProduct, route.Formats); err != nil {
		res = append(res, err)
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindProduct binds and validates parameter Product from path.
func (o *GetImageProductParams) bindProduct(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route
	o.Product = raw

	return nil
}
